import express from 'express';
import Site from '../models/site.js';

const router = express.Router();

// POST route to create a new site with images
router.post('/sites', async (req, res) => {
  try {
    const { sitename, description, location } = req.body;
    const imageFiles = req.files; // Assuming you are using multer to handle file upload for multiple images

    // Check if image files exist
    if (!imageFiles || imageFiles.length === 0) {
      return res.status(400).json({ message: 'Image files are required' });
    }

    // Array to hold uploaded image filenames
    const imageFilenames = [];

    // Save each image filename to array
    for (const imageFile of imageFiles) {
      // Assuming `imageFile.filename` is the filename generated by multer
      imageFilenames.push(imageFile.filename);
    }

    // Create a new site instance with image filenames
    const newSite = new Site({
      sitename,
      description,
      location,
      images: imageFilenames, // Assign array of image filenames to 'images' field
    });

    // Save the new site to the database
    await newSite.save();

    res.status(201).json(newSite);
  } catch (error) {
    console.error('Error creating site:', error);
    res.status(500).json({ message: 'Failed to create site' });
  }
});

export default router;
